### ISSUE TITLE
how to get AOI ard result from overlapping scenes

### ISSUE THREAD

**Issue by jiankang1991** [ESA-PhiLab/OpenSarToolkit#28]
Hi all,

I would like to create Sigma0 product based on OST, since my AOI area contains two different scene which are overlapping. 
How can I get the AOI area Sigma0 product?

Here is an example shown from `s1_grd.plot_inventory`
![image](https://user-images.githubusercontent.com/15608199/76162948-58933680-6142-11ea-9d5e-f856f8f004fa.png)

I just want to get the mosaic result of two overlapping Sigma0 products and crop with the black rectangle?

Which function should I use and how can I find the produced result?

Thank you!

**Comment by BuddyVolly** [comment]
Hi Jiankang, 

are you just using 1 scene per track? Then you could check the Orfeo Mosaic Tool (otbcli_Mosaic on command line). 

Open SAR Toolkit is really about batch processing, and for most applications it makes much more sense to consider time-series instead of single images. So if you want mosaics, you just get them after the time-series processing, and I never tried to process 1 image per track in a time-series, but maybe that works? 

Hope that helps,
BV

**Comment by jiankang1991** [comment]
@BuddyVolly  Thank you for the answer.

**Comment by jiankang1991** [comment]
@BuddyVolly  Maybe another question about my mosaic result, I use gdal to mosaic the two processed RGB tiff tiles. And the result is like this:

![image](https://user-images.githubusercontent.com/15608199/76206461-5ab9cb80-61fc-11ea-80ba-c7906c11cef3.png)

I find that in the land area the value change between these two tiles are small, but it is very obvious in  the sea area. Is it normal or how can I avoid this problem?

For processing the tiles I use 

```
s1_grd.grds_to_ard(
    inventory_df=s1_grd.refined_inventory_dict[key], 
    timescan=True, 
    mosaic=False, 
    subset=s1_grd.aoi,
    overwrite=True
) 
```

Thank you!
