### ISSUE TITLE
What are the differences between different ARD types: CEOS, Earth-Engine, OST-GTC and OST-RTC?

### ISSUE THREAD

**Issue by fangzhegeo** [ESA-PhiLab/OpenSarToolkit#41]
Hi, I'm a little confused about these ARD types. By tracking the fucntion `Sentinel1Scene.get_ard_parameters()`, I known they have different default parameters generated by corresponding json templates. For example, the resolution is 10 of Earth-Engine and CEOS while it's 20 of OST-GTC and OST-RTC.  

I wonder know what are the standards defining these ARD product.  For example, If I set the ARD type to 'Earth-Engine', will the result of `Sentinel1Scene.create_ard()`  be identical to the data downloaded from Google Earth Engine? 

Another question is that what is the best parameter settings to create ARD for flood mapping? I read the [Flood mapping tutorial](http://step.esa.int/docs/tutorials/tutorial_s1floodmapping.pdf) provided by ESA. In this turorial, 5 preprocessing steps are recommend: (1)Orbit file application, (2)Image subset, (3)Radiometric image calibration, (4)Despeckle, (5)Terraion correction, which is different from the default steps of OST. According to default OST-GTC parameters, multi-look is executed but specke filtering and terrain flattening are not eexcuted. So is there a fixed pre-processing workflows which is always best for all GRDH data?

**Comment by BuddyVolly** [comment]
Dear fangzhegeo, 

you are absolutely right and picked up a critical issue in the EO community in general. ARD is different for everybody. Therefore the intent of OST is to provide pre-cooked recipes of what might be interesting to most of the users, plus the possibility to customize processing parameters in whatever way you want, in case you are a more advanced user and have specific requirements. 

Yes, Earth-Engine ARD type does replicate the processing steps of the data as available on Google's Earth Engine, i.e. calibrating to dB scaled Sigma0.

In your last paragraph you are mixing up 2 different processing steps, i.e. terrain flattening and terrain correction. Terrain flattening corrects your radiometry along slopes. Together with the terrain correction, which corrects for geometrical distortions of the image, you receive a Radiometrically Terrain Corrected (RTC) product. Applying Terrain Correction without Terrain Flattening leads to a Geometrical Terrain corrected product (GTC). That's where OST-GTC and OST-RTC definitions come from and differ. Note that terrain flattening is the most computational demanding processing step. 

Now for your case of flood mapping, GTC products are sufficient, since you do not expect floods on slopes. In general, and as a one-size-fits-all ARD type, I recommend OST-RTC, which includes the terrain flattening and the ARD is suitable as well for other types of land cover mapping, or bio-geophysical parameter retrieval. 

Speckle Filtering you need to set manually to True, if you want that. 

I will update the tutorial notebooks within the next days. Stay tuned and check them out, as there is some more information of the ARD types in specific.

Hope that helps

**Comment by fangzhegeo** [comment]
Dear BuddyVolly,

Thanks a lot for your detailed response.  After further experiments, I have understanded these processing steps and the differences between terrain flattinga and terrain correction. By the way, based on my tests,  I found a speckle filtering is very effective that it could remove most of the noise points in flood mapping. 

There is another issue: It seems that ard['apply_ls_mask'] do not work  when creating ARD  even if seted as True. So I need to call GDAL command manully to clip the data by layover-shadow mask.

**Comment by BuddyVolly** [comment]
Dear fangzhegeo, 

thanks for your feedback. I will check the issue with the LS mask (but glad you already found a workaround on your own). 

My philosophy with speckle filtering is that if possible, I apply a multi-temporal one. It is much more effective by taking into account not just the spatial setting, but also the temporal behaviour of a pixel. But that's personal.

In the case of flood mapping, if you just use a single image, you do not have any other choice than using a single-image speckle filter. But if you have time to play around, create a time-series of your AOI, with some 5-10 images of the same track before the flooding event and apply the MT speckle filter, instead of the single (or you can also apply both). It should be favorable, but for strong change throughout the time-series, maybe there will be some artefacts. As you see there is always a trade-off and no definitive answer possible. 

Good luck

**Comment by fangzhegeo** [comment]
Dear BuddyVolly,

Thanks for your professional advice. Today I just starting to read papers which use multi-temporal change detection methods for flood mapping. This is a very timely remider to me.

**Comment by BuddyVolly** [comment]
You are welcome
