### ISSUE TITLE
refine_search crashes if mosaic_refine=False

### ISSUE THREAD

**Issue by vincentvaroquaux** [ESA-PhiLab/OpenSarToolkit#42]
refine_inventory.py:570 datelist is not defined.

I suggest the following:
```
+            datelist, inventory_refined_tmp = _forward_search(
+                aoi_gdf, inventory_refined, area_reduce
+            )
             if mosaic_refine is True:
-                datelist, inventory_refined = _forward_search(
-                    aoi_gdf, inventory_refined, area_reduce
-                )
                 inventory_refined = _backward_search(
-                    aoi_gdf, inventory_refined, datelist, area_reduce
+                    aoi_gdf, inventory_refined_tmp, datelist, area_reduce
                 )
```

**Comment by BuddyVolly** [comment]
Correct, 
but I solved this a bit differently, since I do not want to go through the forward search if it is not needed. 
So I declared a palceholder of datelist with None, and then when it creates the name for the output,  it basically won't take the length of the datelist as it does when mosaic_refine is set to True.
Hope you are fine with this.
